name = "line-of-sight"
main = "src/worker.ts"
compatibility_date = "2026-05-28"
workers_dev = true
preview_urls = false

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[durable_objects.bindings]]
name = "TABLES"
class_name = "GameTable"

[[migrations]]
tag = "v1"
new_classes = ["GameTable"]

[[routes]]
pattern = "los.tre.systems"
custom_domain = true

